### ISSUE TITLE
"fail" inside a LEAVE phaser doesn't work

### ISSUE THREAD

**Issue by timo** [stmuk/p6-Text-VimColour#12]
and perhaps it's not even supposed to work, as when the LEAVE phaser for a method is run, we're "already returning".

This just blew up during a run of perl6-examples.

I'm not sure what the underlying issue is. One of the project euler examples took about 6 minutes of CPU time inside vim, then the command returned with an erroneous error code. It was potentially killed by an ulimit or something?

Anyway, here's a log: http://examples.perl6.org/build-log/build-2016-02-18T00:30+0000.log

**Comment by timo** [comment]
http://examples.perl6.org/build-log/build-2016-02-18T01:15+0000.log  -  this log is after i put in a try block around the invocation of VimColour; since the Failure object now gets created, but attempting to return it from the routine won't work, so the Failure objects get leaked and reported later on.

**Comment by timo** [comment]
```
./categories/euler/prob036-xenu.html:<!-- Error while syntax highlighting this piece of code:  -->
./categories/euler/prob026-shlomif.html:<!-- Error while syntax highlighting this piece of code:  -->
./categories/euler/prob003-hexmode.html:<!-- Error while syntax highlighting this piece of code:  -->
./categories/wsg/beginner-2007/event003-eric256.html:<!-- Error while syntax highlighting this piece of code:  -->
./categories/99-problems/P11-unobe.html:<!-- Error while syntax highlighting this piece of code:  -->
./categories/99-problems/P06-topo.html:<!-- Error while syntax highlighting this piece of code:  -->
./categories/99-problems/P41-rhebus.html:<!-- Error while syntax highlighting this piece of code:  -->
./categories/99-problems/P36-rhebus.html:<!-- Error while syntax highlighting this piece of code:  -->
./categories/rosalind/cstr-grondilu.html:<!-- Error while syntax highlighting this piece of code:  -->
./categories/rosalind/spec-grondilu.html:<!-- Error while syntax highlighting this piece of code:  -->
./categories/rosalind/subs-grondilu.html:<!-- Error while syntax highlighting this piece of code:  -->

```

sadly no proper output for this, but this ought to get you to a broken script faster

**Comment by stmuk** [comment]
die didn't work in the ENTER phaser so both phasers have been removed.
